# common.bash was written by Sylvain Rousseau and modified by Claude Falguiere
#
# Description
# builder configuration

# edit application name
app_name: 'MYAPP'

# edit provisioning profile name
provisioning_profile: 'MYPROFILE'

# the directory where the push script will clone the projet and build
clone_folder: '../privatebuild'

# configuration for mobile store (key based authentication only)
server: 'MY_SERVER'
user: 'USER'
ssh_path: '~/.ssh/id_rsa'
www_path: '/var/www/mobilestore'

# other bundle informations
sign: 'iPhone Developer'
users: 'iPad de Valtech'
